### ISSUE TITLE
Unordered Bounded Representation

### ISSUE THREAD

**Issue by khozzy** [m4saka/xcs-xcsr#2] opened 2018-10-13 07:16 UTC
Do you plan to add **UBR** (_unordered bounded representation_) to XCSR?

Having **OBR** (_ordered bounded representation_), which is LU in your case would be pretty simple and probably make [this](http://eprints.uwe.ac.uk/5887/) paper nicely reproducible.

Regards and thanks for your work.

**Comment by m4saka** [comment] 2018-10-13 07:58
Thank you for letting me know about UBR.
Yes, I can work on it.  I will start off by checking that paper.

**Comment by m4saka** [comment] 2018-10-13 22:31
I have finished checking the paper.
And I figured out my implementation is a bit different from that paper in crossover, and UBR would not make any improvement because of this difference.

In my implementation, a gene is a dimension (including lower and upper values), then crossover doesn't break the tuple (l, u).
On the other hand, the paper implies crossover occurs in lower and upper values individually, and if that is, Ordered Bound Representation (OBR) has the bias issue mentioned in the paper.

In other words...

- My Implementation:  
Parent 1: (**lu**)(**lu**)(**lu**)(**lu**)(**lu**)(**lu**)  
Parent 2: (lu)(lu)(lu)(lu)(lu)(lu)  
↓  
Child 1: (**lu**)(**lu**)(lu)(lu)(**lu**)(**lu**)  
Child 2: (lu)(lu)(**lu**)(**lu**)(lu)(lu)

- The paper:  
Parent 1: **lulululululu**  
Parent 2: lulululululu  
↓  
Child 1: **lul**ululu**lulu**  
Child 2: lul**ululu**lulu  

I have also checked the implementation of xcslib (http://xcslib.sourceforge.net/) by Lanzi, the crossover operator is based on the same idea as the second one, so I guess that is more common than my implementation.

UBR has an advantage over OBR only when a new condition pair (p, q) is created by values from two different classifiers in crossover.
Thus, there would be no performance change even if UBR is introduced for now because currently (l, u) tuples cannot be broken by crossover.

I will begin with working on changing the crossover operator to the common method first.

**Comment by m4saka** [comment] 2018-10-14 00:13
Modified the XCSR crossover operators. #3

**Comment by m4saka** [comment] 2018-10-14 02:03
UBR implementation finished in `feature/unordered_bound_repr` branch.

Still not tested enough yet, but it looks working well in 6-bit real multiplexer problem.

The paper doesn't have a performance comparison between OBR and UBR, so I don't know if there are improvements in performance.
The performance ranking and the macro-classifier count ranking for OBR vs UBR varies depending on random seeds.

* 6-bit real multiplexer problem

    * Reward average (over 100 iterations)
    ![reward](https://user-images.githubusercontent.com/14288724/46911745-18a53f80-cfa0-11e8-9f4a-06536ed7d7fe.png)

    * The number of macro-classifiers
    ![num](https://user-images.githubusercontent.com/14288724/46911746-1ba03000-cfa0-11e8-84d4-91fc16735d3c.png)

Anyway, next I will work on the checker board problem to reproduce the results.

**Comment by khozzy** [comment] 2018-10-14 10:36
Great. I have also just implemented checkerboard (in Python).
Take a [look](https://github.com/ParrotPrediction/openai-envs/blob/master/gym_checkerboard/checkerboard.py) if you want. Later on I still would like to compare your XCSR with rACS

**Comment by khozzy** [comment] 2018-10-14 14:56
@m4saka, would be interested in co-authoring a research paper comparing real-value representation both for XCSR and rACS?

**Comment by m4saka** [comment] 2018-10-23 23:19
I'm very sorry for my late reply.
I have finished implementing the checkerboard problem, but after that, it took so long time to reproduce the result of Figure 15 in the paper.

I managed to reproduce the result today...

The problem was that the covering operator imprementation in this paper is a bit different from the common XCSR imprementations used in xcslib by Lanzi.
It seems that they truncate the random range of covering to the range [0, 1) before generating intervals. With the common imprementation, if you set s_0 to 1.0, too many max-range intervals (equivalent of "#") are generated for the classifier's initial condition in covering, so too many initial "#"s caused a remarkable decrease in the system performance of the checkerboard problem depending on random seeds.

In other words, if s_0 is 1.0, the covering procedure is ...  

- In the common XCSR implementation,
    1. l <- x - rand(0, s_0)  
       u <- x + rand(0, s_0)
    2. if (l < 0) l <- 0  
       if (u > 1) u <- 1

- In the UBR paper,
    1. if (x - s_0 < 0) l_min <- 0  
       else l_min <- x - s_0  
       if (x + s_0 > 1) u_max <- 1  
       else u_max <- x + s_0  
    2. l <- rand(l_min, x)  
       u <- rand(x, u_max)

(I chose OBR for this example for simplicity, but there is the same difference in UBR.)

In the first implementation, random intervals like (-0.4, 0.3) and (-0.1, 0.5) is generated, and both are truncated to (0.0, 1.0).  Then (0.0, 1.0) appears very likely.
In the second one, generated random intervals are always contained in the range [0.0, 1.0), so initial intervals tend to have small spread values, which is desirable in the checkerboard problem.

I added the option `--do-covering-random-range-truncation` to reproduce the second one.

This is the same settings as the experiment for Figure 15 in the paper.

```
$ ./xcsr --chk=3 --chk-div=3 -i 100000 --sma=50 --avg-seeds=10 --repr=ub -N 800 --beta=0.2 --alpha=0.1 --epsilon-0=10 --nu=5 --theta-ga=12 --chi=0.8 --mu=0.04 --theta-del=20 --delta=0.1 --theta-sub=20 --initial-prediction=10 --initial-prediction-error=0 --initial-fitness=0.01 --max-mutation=0.1 --s-0=1.0 --do-action-set-subsumption=false --do-covering-random-range-truncation=true --coutput=chk3x3x3_classifier_ub.csv --routput=chk3x3x3_reward_ub.csv --noutput=chk3x3x3_num_ub.csv
```

![output](https://user-images.githubusercontent.com/14288724/47396399-7cc8c000-d765-11e8-96ae-91351c519580.png)

**Comment by m4saka** [comment] 2018-10-23 23:33
@khozzy,
 
> @m4saka, would be interested in co-authoring a research paper comparing real-value representation both for XCSR and rACS?

That would be nice!
But we need multi-step benchmark problems for comparing XCSR and rACS in the same problem, right?
Or would we evaluate the differences among the representations for XCSR and rACS separately?

**Comment by khozzy** [comment] 2018-10-31 08:05
> But we need multi-step benchmark problems for comparing XCSR and rACS in the same problem, right?
Or would we evaluate the differences among the representations for XCSR and rACS separately?

I still need some fixes for my version of algorithm. I will get back to you when it will be finished to agreed for some next steps.

**Comment by m4saka** [comment] 2018-11-13 14:06
The implementation of UBR itself is completed, so I would like to close this issue.
But feel free to post a comment here (or contact me at this email address: tadokoro@uec.ac.jp).

**Closed by m4saka** 2018-11-13 14:06 UTC
Labels: enhancement

**Comment by khozzy** [comment] 2018-11-14 06:49
Great, thanks.
